### ISSUE TITLE
Enigmatica 2 v1.69a Server Iron Chest Shulker box crash

### ISSUE THREAD

**Issue by Kaiagarro** [progwml6/ironshulkerboxes#1]
## Version Information
`Minecraft: `1.12.2
`Forge: `14.23.5.2836
`Iron Shulker Boxes: ` ironchest-1.12.2-7.0.69.845

## Report Information

Applied the Iron Chest to Gold Chest upgrade to Iron Shulker box and crashed my client on a private server using the Enigmatica 2 1.69a modpack with no alterations to the mods.
## Steps to Reproduce

Play on server, crash. I can only assume it is reproduced by applying the upgrade while the Iron Shulker Chest is still within the player's inventory.
## Crash Log

<script src="https://gist.github.com/Kaiagarro/087c54f6fda0ff37a10f5114634c1fee.js"></script>
## Forge Log

I don't know where to find this no matter how much I have looked and researched.

**Comment by alexbegt** [comment]
Can you upload the crash report again? I am unable to view it.

**Comment by alexbegt** [comment]
Please update to the latest version of Quark. This will fix the crash.
