### ISSUE TITLE
Crash when upgrading Iron Shulker boxes - 1.16.1

### ISSUE THREAD

**Issue by theCrimson247** [progwml6/ironshulkerboxes#12]
## Version Information
`Minecraft:1.16.1 `
`Forge: 32.0.0.1`
`Iron Shulker Boxes:16.1-5.0.1 `

## Report Information
When using the gold upgrade on an iron shulker, the server forcibly crashes.

## Steps to Reproduce
Place the iron shulker, then from your hotbar, right click on it with the iron to gold upgrade module.

## Crash Log
https://pastebin.com/Jq53bnSx

## Forge Log
https://pastebin.com/kYygg3zF

**Comment by MrDj200** [comment]
Can confirm.
Also having the issue

**Comment by Gbergz** [comment]
Currently having the same issues on a server, resulting in it crashing.

**Crash-Report**: https://hatebin.com/sziwriwnmo

**Modpack**: https://www.curseforge.com/minecraft/modpacks/tnp-limitless-3

**Minecraft Version**: 1.16.3
**Forge Version**: 34.1.42
**Iron Shulkerboxes Version**: 1.16.4-5.1.9

**Comment by alexbegt** [comment]
Please try the latest release to see if this issue still occurs, and if so, open a new ticket :)
