### ISSUE TITLE
Dupe bug between Quark and Iron Shulker Boxes

### ISSUE THREAD

**Issue by GSValore** [progwml6/ironshulkerboxes#14]
## Version Information
`Minecraft: ` 1.16.3, 1.16.4
`Forge: ` 34.1.42, 35.0.18
`Iron Shulker Boxes: ` 5.1.2, 5.1.9
`Quark:` 274, 276

## Report Information

Duplication bug between quark's right-click on shulker box feature and iron shulker boxes.  Boxes can be replicated by simply right-clicking with a stack to split it/insert.

## Steps to Reproduce

1. Create a few Iron Shulker Boxes, minimum of 4 required.
2. Attempt to split the stack by right-clicking and it gets inserted.
3. Inspect the remaining half-stack to find each shulker box now contains a copy of the original half.  This is not limited to the shulker boxes; if the contents of the stacks are identical then you can duplicate any resources as well.

## Additional Information

This can be mitigated currently by disabling Quark's right-click feature.

**Comment by Vazkii** [comment]
bruh why are they stackable

**Comment by alexbegt** [comment]
They shouldn't be stackable... I am sorry that I finally fixed this issue, been extremely busy with college work
