### ISSUE TITLE
Crushing when upgrading shulker boxes

### ISSUE THREAD

**Issue by Lived1337** [progwml6/ironshulkerboxes#15]
## Version Information
`Minecraft: ` 1.16.4
`Forge: ` 35.1.3
`Iron Shulker Boxes: `  5.1.9

## Report Information
 My server crashing when I want to upgrade shulker boxes

## Steps to Reproduce
 Try to upgrade shulker box

## Crash Log
 https://pastebin.com/FEXWrZm0

## Forge Log
 idk why server doesn't make this file

**Comment by alexbegt** [comment]
This has been resolved and a new version will be posted soon.
