### ISSUE TITLE
Exception in Server Tick Loop when attempting to upgrade dyed Shulker Boxes

### ISSUE THREAD

**Issue by Algester** [progwml6/ironshulkerboxes#22]
## Version Information
`Minecraft: 1.16.4` 
`Forge: 35.1.11` 
`Iron Chests: Iron Chest 1.16.4-11.2.10` 

## Report Information
NoSuchMethodError 

## Steps to Reproduce
This is on a server
Dye a Shulker Box (in my case Cyan), then upgrade it to Iron Shulker Box and then Upgrade it to Gold Shulker Box the server then crashes

## Crash Log
Attached is the Server Log
[latest.log](https://github.com/progwml6/ironchest/files/5764002/latest.log)

## Forge Log
[crash-2021-01-04_17.23.10-server.txt](https://github.com/progwml6/ironchest/files/5764008/crash-2021-01-04_17.23.10-server.txt)

**Comment by alexbegt** [comment]
This has been resolved a new version will be posted soon.
