### ISSUE TITLE
Please release a new jar for fix crystal shulker crash

### ISSUE THREAD

**Issue by zorc** [progwml6/ironshulkerboxes#23]
Please release a new jar for fix crystal shulker crash in mc 1.16.4,thank you very much.

**Comment by alexbegt** [comment]
A new release has been uploaded to curseforge.

**Comment by SakakiChizuru** [comment]
> A new release has been uploaded to curseforge.

New release is missing mods.toml. Can use old ones tho.
@alexbegt

**Comment by alexbegt** [comment]
Give 5.1.11 a try, should resolve this.
