### ISSUE TITLE
5.1.10 file is invalid (1.16.4)

### ISSUE THREAD

**Issue by brisingraerowing** [progwml6/ironshulkerboxes#25]
## Version Information
`Minecraft: ` 1.16.4
`Forge: `  35.1.36
`Iron Shulker Boxes: ` 5.1.10

## Report Information
Forge spits out an error screen stating that the mod file is invalid.

## Steps to Reproduce
Load the 5.1.10 file in an instance.

## Crash Log
No crash log

## Forge Log
[Latest and Debug Logs](https://gist.github.com/BrisingrAerowing/bb71abe1f9eea18c02e07e65182afbd2)

**Comment by alexbegt** [comment]
Please try with 5.1.11. If this still occurs, please open a new ticket.

**Comment by brisingraerowing** [comment]
The new version works.
