### ISSUE TITLE
Items are being deleted 

### ISSUE THREAD

**Issue by Superdude06** [progwml6/ironshulkerboxes#26]
Items are deleted when upgrading an iron shulker to a gold and a gold shulker to a diamond; I have no tried others.

Normal to iron shulker works tho.

I am running latest version of forge

**Comment by Iashar** [comment]
Is it possible to put this fix out, or is it still being worked on?
Amazing mod, but this is slightly game breaking.
Thank you for your quick fixes when you see bugs!
