### ISSUE TITLE
Crash on upgrading in-world

### ISSUE THREAD

**Issue by Xaikii** [progwml6/ironshulkerboxes#7]
## Version Information
`Minecraft: 1.14.4`
`Forge: forge-28.1.109`
`Iron Shulker Boxes: 1.14.4-3.1.12`

## Report Information

Crafted a White Iron Shulker Box, used an iron to gold upgrade, crash
## Steps to Reproduce

Crafted a White Iron Shulker Box, used an iron to gold upgrade, crash
## Crash Log

https://pastebin.com/u5kda4c3

**Comment by alexbegt** [comment]
This issue has been fixed for 1.16. If this still occurs please reopen a new ticket.
