### ISSUE TITLE
Upgrading Shulker Boxes In 1.14

### ISSUE THREAD

**Issue by SpookyTheOoze** [progwml6/ironshulkerboxes#8]
## Version Information
`Minecraft: ` 1.14
`Forge: ` 28.1.61
`Iron Shulker Boxes: ` 1.14.4-3.1.12

## Report Information
I am not certain whether this occurs when you upgrade ALL Shulker Boxes, but at least when you upgrade from Diamond to Crystal it'll delete every single item you have in the Diamond Shulker Box when you apply the Crystal Upgrade.

## Steps to Reproduce
Apply a Crystal to Diamond Shulker Box Upgrade while having stuff in the Diamond Shulker Box. 

## Forge Log
[2020-03-07-1.log.gz](https://github.com/progwml6/ironshulkerboxes/files/4302267/2020-03-07-1.log.gz)

**Comment by alexbegt** [comment]
This issue has been fixed for 1.16. If this still occurs please reopen a new ticket.
